### ISSUE TITLE
Create Iteration 4 DATA continued...

### ISSUE THREAD

**Issue by MTCawthray** [MTCawthray/FitLit#11]
- [x] Method to show average sleep quality for all users
- [ ] Method to show all users who average a sleep quality greater than 3 for a given week (not just the latest week)
- [ ] Method to find users who slept the most number of hours identified by the date (1 or more if they tied) 
    > ask question about how many users we are actually returning? Only one unless there is a tie then we return how ever many tied?

**Comment by madhaus4** [comment]
don't need the last 2 methods per Hannah's post in slack
